// Auto-generated by: npx supabase gen types typescript --project-id qgalaewrpqvdpfuuwlrs --schema public
// Do not edit manually — regenerate after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      catastrophe_care_requirements: {
        Row: {
          care_state: Database["public"]["Enums"]["care_state"]
          created_at: string
          display_order: number
          field_label: string
          field_name: string
          field_options: Json | null
          field_type: Database["public"]["Enums"]["field_type"]
          id: string
          is_active: boolean
          is_required: boolean
          organization_id: string
          provider_id: string | null
          provider_type: string | null
          updated_at: string
        }
        Insert: {
          care_state: Database["public"]["Enums"]["care_state"]
          created_at?: string
          display_order?: number
          field_label: string
          field_name: string
          field_options?: Json | null
          field_type?: Database["public"]["Enums"]["field_type"]
          id?: string
          is_active?: boolean
          is_required?: boolean
          organization_id: string
          provider_id?: string | null
          provider_type?: string | null
          updated_at?: string
        }
        Update: {
          care_state?: Database["public"]["Enums"]["care_state"]
          created_at?: string
          display_order?: number
          field_label?: string
          field_name?: string
          field_options?: Json | null
          field_type?: Database["public"]["Enums"]["field_type"]
          id?: string
          is_active?: boolean
          is_required?: boolean
          organization_id?: string
          provider_id?: string | null
          provider_type?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      catastrophe_family_contacts: {
        Row: {
          created_at: string
          id: string
          is_emergency_contact: boolean
          nombre_contacto: string
          notas: string | null
          organization_id: string
          relacion: string
          telefono_internacional: string | null
          telefono_nacional: string | null
          updated_at: string
          victim_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_emergency_contact?: boolean
          nombre_contacto: string
          notas?: string | null
          organization_id: string
          relacion: string
          telefono_internacional?: string | null
          telefono_nacional?: string | null
          updated_at?: string
          victim_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_emergency_contact?: boolean
          nombre_contacto?: string
          notas?: string | null
          organization_id?: string
          relacion?: string
          telefono_internacional?: string | null
          telefono_nacional?: string | null
          updated_at?: string
          victim_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "catastrophe_family_contacts_victim_id_fkey"
            columns: ["victim_id"]
            isOneToOne: false
            referencedRelation: "catastrophe_victims"
            referencedColumns: ["id"]
          },
        ]
      }
      catastrophe_victim_info: {
        Row: {
          alergias: string | null
          case_id: string | null
          condiciones_preexistentes: string | null
          created_at: string
          estado_destino: Database["public"]["Enums"]["care_state"]
          fecha_hora_entrada: string
          id: string
          motivo_principal_consulta: string | null
          organization_id: string
          tratamiento_medicamentos: string | null
          triage_category: Database["public"]["Enums"]["triage_category"]
          updated_at: string
          victim_id: string
        }
        Insert: {
          alergias?: string | null
          case_id?: string | null
          condiciones_preexistentes?: string | null
          created_at?: string
          estado_destino?: Database["public"]["Enums"]["care_state"]
          fecha_hora_entrada?: string
          id?: string
          motivo_principal_consulta?: string | null
          organization_id: string
          tratamiento_medicamentos?: string | null
          triage_category: Database["public"]["Enums"]["triage_category"]
          updated_at?: string
          victim_id: string
        }
        Update: {
          alergias?: string | null
          case_id?: string | null
          condiciones_preexistentes?: string | null
          created_at?: string
          estado_destino?: Database["public"]["Enums"]["care_state"]
          fecha_hora_entrada?: string
          id?: string
          motivo_principal_consulta?: string | null
          organization_id?: string
          tratamiento_medicamentos?: string | null
          triage_category?: Database["public"]["Enums"]["triage_category"]
          updated_at?: string
          victim_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "catastrophe_victim_info_victim_id_fkey"
            columns: ["victim_id"]
            isOneToOne: true
            referencedRelation: "catastrophe_victims"
            referencedColumns: ["id"]
          },
        ]
      }
      catastrophe_victims: {
        Row: {
          cedula: string | null
          created_at: string
          edad: number | null
          genero: string | null
          id: string
          nombre_completo: string
          nombre_edificio_casa: string | null
          notas: string | null
          numero_apartamento_casa: string | null
          organization_id: string
          registration_number: string
          sector_comunidad: string | null
          telefono_contacto: string | null
          ubicacion_actual_refugio: string | null
          updated_at: string
        }
        Insert: {
          cedula?: string | null
          created_at?: string
          edad?: number | null
          genero?: string | null
          id?: string
          nombre_completo: string
          nombre_edificio_casa?: string | null
          notas?: string | null
          numero_apartamento_casa?: string | null
          organization_id: string
          registration_number: string
          sector_comunidad?: string | null
          telefono_contacto?: string | null
          ubicacion_actual_refugio?: string | null
          updated_at?: string
        }
        Update: {
          cedula?: string | null
          created_at?: string
          edad?: number | null
          genero?: string | null
          id?: string
          nombre_completo?: string
          nombre_edificio_casa?: string | null
          notas?: string | null
          numero_apartamento_casa?: string | null
          organization_id?: string
          registration_number?: string
          sector_comunidad?: string | null
          telefono_contacto?: string | null
          ubicacion_actual_refugio?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      care_state:
        | "Triaje"
        | "En Atención"
        | "Hospitalizado"
        | "Transferido"
        | "Alta Médica"
        | "Anulado"
      field_type:
        | "text"
        | "textarea"
        | "select"
        | "boolean"
        | "number"
        | "date"
        | "datetime"
        | "file"
      triage_category: "Rojo" | "Amarillo" | "Verde"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      care_state: [
        "Triaje",
        "En Atención",
        "Hospitalizado",
        "Transferido",
        "Alta Médica",
        "Anulado",
      ],
      field_type: [
        "text",
        "textarea",
        "select",
        "boolean",
        "number",
        "date",
        "datetime",
        "file",
      ],
      triage_category: ["Rojo", "Amarillo", "Verde"],
    },
  },
} as const

// Convenience aliases used across API routes
export type TriageCategory = Database["public"]["Enums"]["triage_category"]
export type CareState = Database["public"]["Enums"]["care_state"]
export type FieldType = Database["public"]["Enums"]["field_type"]

export type CatastropheVictim = Tables<"catastrophe_victims">
export type InsertCatastropheVictim = TablesInsert<"catastrophe_victims">
export type UpdateCatastropheVictim = TablesUpdate<"catastrophe_victims">

export type CatastropheVictimInfo = Tables<"catastrophe_victim_info">
export type InsertCatastropheVictimInfo = TablesInsert<"catastrophe_victim_info">
export type UpdateCatastropheVictimInfo = TablesUpdate<"catastrophe_victim_info">

export type CatastropheFamilyContact = Tables<"catastrophe_family_contacts">
export type InsertCatastropheFamilyContact = TablesInsert<"catastrophe_family_contacts">
export type UpdateCatastropheFamilyContact = TablesUpdate<"catastrophe_family_contacts">

export type CatastropheCareRequirement = Tables<"catastrophe_care_requirements">
export type InsertCatastropheCareRequirement = TablesInsert<"catastrophe_care_requirements">
export type UpdateCatastropheCareRequirement = TablesUpdate<"catastrophe_care_requirements">
